project:
  type: website
  resources:
    - references.bib
website:
  favicon: assets/logos/logo-dml-white-en.png
  site-url: "https://iat-dml.github.io"
  repo-url: "https://github.com/iat-dml/iat-dml.github.io"
  title: "Data and Modelling Infrastructure for Living Labs"
  description: "This is the website of the Data and Modelling Infrastructure for Living Labs Working group (SWG) of the Innovation Center for Agricultural System Transformation (IAT) as part of the Liebniz Center for Agricultural Landscape Research (ZALF)." 
  page-footer: |
      ![](/assets/footer-light.png){fig-alt="Banner of partners" width=100% .light-content}![](/assets/footer-dark.png){fig-alt="Banner of partners" width=100% .dark-content} {{< fa regular copyright >}} Benjamin Black, 2026 All content licensed under {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/) · [Privacy policy](privacy-policy.qmd)
  navbar:
    # logo: false
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: People
      - href: team.qmd
        text: Projects
      - href: news.qmd
        text: News    
      - href: resources.qmd
        text: Resources
      - menu:
              - href: code-of-conduct.qmd
                text: Code of Conduct
              - href: charter.qmd
                text: Charter
        text: "About"
      - icon: github
        href: https://github.com/iat-dml
      - icon: envelope
        aria-label: email
        href: "mailto:benjaminsamuel.black@zalf.de"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [scss/styles.scss]
      # dark: [scss/styles.scss]
    include-after-body:
      - file: hero.html
    toc: false
    page-layout: full        # or "article" (default, narrow), "custom"
    max-width: 1400px        # Adjust to your preference
    margin-left: 2rem
    margin-right: 2rem
lightbox: true
brand:
  light: light-brand.yml
  # dark: dark-brand.yml

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: de
    text: "DE"
  - name: en
    text: "ENG"
  mainlanguage: 'en'
  languages: ['de']
title-de: Arbeitsgruppe „Daten- und Modellierungsinfrastruktur für Living Labs“
description-de: „Dies ist die Website der Arbeitsgruppe „Daten- und Modellierungsinfrastruktur für Living Labs“ (SWG) des Innovationszentrums für Agrarsystemtransformation (IAT) als Teil des Leibniz-Zentrums für Agrarlandschaftsforschung (ZALF).“
author-de: author in de
lang: en

