
project:
  type: website
  resources:
    - references.bib
website:
  site-url: https://example.com
  title: "Data and Modelling Infrastructure for Living Labs Working group"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - menu:
              - team.qmd
        text: "About"
      - icon: github
        href: https://github.com/zalf-lli
      - icon: envelope
        aria-label: email
        href: "mailto:benjaminsamuel.black@zalf.de"



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: de
    text: "Version in de"
  - name: en
    text: "Version in en"
  mainlanguage: 'en'
  languages: ['de']
title-de: title in de
description-de: description in de
author-de: author in de
lang: en

