
project:
  type: website
  resources:
    - references.bib
website:
  site-url: "https://DaMIfLL.github.io"
  repo-url: "https://github.com/zalf-lli/DaMIfLL.github.io"
  title: "Data and Modelling Infrastructure for Living Labs Working group"
  description: "This is the website of the Data and Modelling Infrastructure for Living Labs Working group (SWG) of the Innovation Center for Agricultural System Transformation (IAT) as part of the Liebniz Center for Agricultural Landscape Research (ZALF)."
  page-footer:
    left: |
      {{< fa regular copyright >}} Benjamin Black, 2026<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with [Quarto](https://quarto.org/)<br>
  navbar:
    right:
      - href: index.qmd
        text: Home      
      - href: resources.qmd
        text: Resources
      # - href: news.qmd
      #   text: News
      - menu:
              - href: team.qmd
                text: People
              - href: code-of-conduct.qmd
                text: Code of Conduct
              - href: charter.qmd
                text: Charter
        text: "About"
      - icon: github
        href: https://github.com/zalf-lli
      - icon: envelope
        aria-label: email
        href: "mailto:benjaminsamuel.black@zalf.de"




format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: de
    text: "DE"
  - name: en
    text: "ENG"
  mainlanguage: 'en'
  languages: ['de']
title-de: Arbeitsgruppe „Daten- und Modellierungsinfrastruktur für Living Labs“
description-de: „Dies ist die Website der Arbeitsgruppe „Daten- und Modellierungsinfrastruktur für Living Labs“ (SWG) des Innovationszentrums für Agrarsystemtransformation (IAT) als Teil des Leibniz-Zentrums für Agrarlandschaftsforschung (ZALF).“
author-de: author in de
lang: en

