---
title: "Support anfordern"
---

Verwenden Sie das untenstehende Formular, um uns eine Anfrage zu senden – es ist keinerlei Konto erforderlich.

::: {.callout-note title="So werden Ihre Daten behandelt" collapse="true"}
Die von Ihnen übermittelten Informationen (Name, Zugehörigkeit, E-Mail-Adresse und Beschreibung Ihrer Anfrage)
werden ausschließlich zur Bearbeitung Ihrer Serviceanfrage verwendet. Sie werden in der Microsoft 365-Umgebung von ZALF empfangen und automatisch in ein „Issue“ zur Arbeitsverfolgung in unserem GitHub-Repository (GitHub, Inc., USA) übertragen, wo unser Team die Anfragen bearbeitet. Die Daten werden gelöscht, sobald sie nicht mehr benötigt werden. **Bitte geben Sie keine sensiblen personenbezogenen Daten** (z. B. Gesundheitsdaten) oder
vertrauliche Forschungsdaten an – wir werden Sie über einen geeigneten Kanal um weitere Details bitten,
sobald wir mit Ihnen in Kontakt getreten sind.
:::

<iframe src="https://forms.office.com/Pages/ResponsePage.aspx?id=Zo0M4kenHkul2ga1P95PoHFKJd1yMPxBpP7fDZSCehNUOFhRWTJBMEo1QVRNN1dKT1lZUjRJOUJRRi4u&embed=true" frameborder="0" marginwidth="0" marginheight="0" style="border: none; width: 100%; height: 80vh; min-height: 480px;" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

::: {.column-margin}
**Das Formular wird nicht geladen?**
[In einem neuen Tab öffnen](https://forms.office.com/Pages/ResponsePage.aspx?id=Zo0M4kenHkul2ga1P95PoHFKJd1yMPxBpP7fDZSCehNUOFhRWTJBMEo1QVRNN1dKT1lZUjRJOUJRRi4u){target="_blank"}
:::

## Bevorzugen Sie E-Mail?

Schreiben Sie uns an [iat-dml@zalf.de](mailto:iat-dml@zalf.de){.dml-contact} mit einer kurzen Beschreibung Ihrer Anfrage –
diese wird automatisch in unserem Tracking-System erfasst und wir melden uns bei Ihnen.

## Haben Sie bereits ein GitHub-Konto?

Sie können eine Anfrage direkt in unserem
[Service Desk](https://github.com/iat-dml/service-desk/issues/new/choose) erstellen.